# Jekyll configuration

name: Denismes
description: Développement web et astuces pour débutants

# url is currently only used only for the RSS feed in feed.xml
url: 

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/xixia'
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "fr" 

paginate: 5

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate', 'jekyll-sitemap']


exclude: ['README.md', 'LICENSE', "*.bak"]
